require: rubocop-rspec

AllCops:
  DisplayCopNames: true

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - tide-api.gemspec

Metrics/LineLength:
  Max: 120

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false