AllCops:
  DisplayCopNames: true

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - tide-api.gemspec

Metrics/LineLength:
  Max: 120

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false